[build]
  command = "npm run build"
  publish = ".next"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


  [[redirects]]
  from = "/proxy/*"
  to = "https://api.openai.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

