[build]
  command = "npm run build"
  publish = ".next"
  edge_functions = "edge-functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200